<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <VARIABLE id="LETI_DIR" value="$_DIR_$" override="true"/>
  <DEFINE>
    <MAN_AUTO_SWITCH base_type="IMAGE_PARAM_BUTTON" opacity="0.7" image="$LETI_DIR$\CMT\auto_manual.png" image_mouse_mask="" cursor="system::hand" />
    <MUTE_SWITCH base_type="IMAGE_PARAM_BUTTON" opacity="1" image="$LETI_DIR$\CMT\mute_on_off.png" image_mouse_mask="" cursor="system::hand" />
    <PAUSE_SWITCH base_type="IMAGE_PARAM_BUTTON" opacity="1" image="$LETI_DIR$\CMT\pause_play.png" image_mouse_mask="" cursor="system::hand" />
    <MORE_INFO_SWITCH base_type="IMAGE_PARAM_BUTTON" opacity="1" image="$LETI_DIR$\CMT\more_info.png" image_mouse_mask="" cursor="system::hand" />
    <SAVE_SNAPSHOT base_type="IMAGE_PARAM_METER" opacity="1" images_count="4" image="$LETI_DIR$\CMT\save_snapshot.png" image_mouse_mask="" cursor="system::hand" />
    <LCD_H_SWITCH_WHITE base_type="IMAGE_PARAM_BUTTON" opacity="0.8" image="$LETI_DIR$\CMT\lcd_h_switch_white.png" image_mouse_mask="" cursor="system::hand" />
    <INVISIBLE_BUTTON_54x30 base_type="IMAGE_PARAM_BUTTON" opacity="0" image="$LETI_DIR$\CMT\button_54x30.png" image_mouse_mask="" images_count="2" cursor="system::hand" />
    <SWITCH_SLIDER base_type="IMAGE_PARAM_SLIDER" orientation="vertical" image="$LETI_DIR$\CMT\graph_slider.png" image_mask="" thumb_image="$LETI_DIR$\CMT\graph_slider_thumb.png" cursor="system::hand"/>
    <LCD_BUTTON base_type="IMAGE_PARAM_BUTTON" orientation="vertical" image="$LETI_DIR$\CMT\lcd_button_down.png" image_mask="" thumb_image="$LETI_DIR$\CMT\lcd_button_down.png" cursor="system::hand" opacity="90%" v_offset="1" />

    <!-- orange -->
    <ORANGE_SWITCH_SLIDER base_type="IMAGE_PARAM_SLIDER" orientation="vertical" image="$LETI_DIR$\CMT\graph_slider.png" image_mask="" thumb_image="$LETI_DIR$\CMT\orange_graph_slider_thumb.png" cursor="system::hand"/>
    <ORANGE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$LETI_DIR$\CMT\orange_knob.png" image_hover="$LETI_DIR$\CMT\orange_knob.png" image_focus="$LETI_DIR$\CMT\orange_knob.png" image_pushed="$LETI_DIR$\CMT\orange_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <ORANGE_MINI_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$LETI_DIR$\CMT\orange_mini_knob.png" image_hover="$LETI_DIR$\CMT\orange_mini_knob.png" image_focus="$LETI_DIR$\CMT\orange_mini_knob.png" image_pushed="$LETI_DIR$\CMT\orange_mini_knob.png" images_count="73" positions_count="73" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <ORANGE_ON_OFF_SWITCH base_type="IMAGE_PARAM_BUTTON" image="$LETI_DIR$\CMT\orange_on_off.png" image_mouse_mask="" cursor="system::hand"/>

  </DEFINE>
</DUMMY>